<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

// Import semua model yang dipakai sebagai referensi class name
use App\Models\DataLapanganAir;
use App\Models\DataLapanganKebisingan;
use App\Models\DataLapanganKebisinganPersonal;
use App\Models\DataLapanganCahaya;
use App\Models\DataLapanganEmisiKendaraan;
use App\Models\DataLapanganGetaran;
use App\Models\DataLapanganGetaranPersonal;
use App\Models\DataLapanganIklimPanas;
use App\Models\DataLapanganIklimDingin;
use App\Models\DataLapanganPartikulatMeter;
use App\Models\DataLapanganLingkunganHidup;
use App\Models\DataLapanganLingkunganKerja;
use App\Models\DataLapanganMicrobiologi;
use App\Models\DataLapanganMedanLM;
use App\Models\DataLapanganSinarUv;
use App\Models\DataLapanganDirectLain;
use App\Models\DataLapanganSwab;
use App\Models\DataLapanganEmisiCerobong;
use App\Models\DataLapanganErgonomi;
use App\Models\DataLapanganIsokinetikSurveiLapangan;
use App\Models\DataLapanganIsokinetikPenentuanKecepatanLinier;
use App\Models\DataLapanganIsokinetikBeratMolekul;
use App\Models\DataLapanganIsokinetikKadarAir;
use App\Models\DataLapanganIsokinetikPenentuanPartikulat;
use App\Models\DataLapanganIsokinetikHasil;
use App\Models\DataLapanganDebuPersonal;
use App\Models\DataLapanganPsikologi;
use App\Models\DataLapanganSenyawaVolatile;
use App\Models\DetailLingkunganHidup;
use App\Models\DetailLingkunganKerja;
use App\Models\DetailMicrobiologi;
use App\Models\DetailSenyawaVolatile;
// ... import lainnya sesuai kebutuhan
use Carbon\Carbon;
Carbon::setLocale('id');
class RequiredParameterSeeder extends Seeder
{
    public function run()
    {
        $data_parameters = [
            ["parameter" => "Air", "requiredCount" => 1, "category" => "1-Air", "model" => DataLapanganAir::class, "model2" => null],
            ["parameter" => "Debu (P8J)", "requiredCount" => 2, "category" => "4-Udara", "model" => DataLapanganDebuPersonal::class, "model2" => null],
            ["parameter" => "Asam Asetat (8 jam)", "requiredCount" => 2, "category" => "4-Udara", "model" => DataLapanganIklimPanas::class, "model2" => null],
            ["parameter" => "Karbon Hitam (8 jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganDebuPersonal::class, "model2" => null],
            ["parameter" => "PM 10 (Personil)", "requiredCount" => 2, "category" => "4-Udara", "model" => DataLapanganDebuPersonal::class, "model2" => null],
            ["parameter" => "PM 2.5 (Personil)", "requiredCount" => 2, "category" => "4-Udara", "model" => DataLapanganDebuPersonal::class, "model2" => null],
            ["parameter" => "Xylene secara personil sampling (SC)", "requiredCount" => 2, "category" => "4-Udara", "model" => DataLapanganDebuPersonal::class, "model2" => null],
            ["parameter" => "C O", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "Co", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "CO (24 Jam)", "requiredCount" => 4, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "CO (6 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "CO (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "CO2", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "CO2 (24 Jam)", "requiredCount" => 4, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "CO2 (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "H2CO", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "HCHO (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "O2", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "VOC", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "VOC (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganDirectLain::class, "model2" => null],
            ["parameter" => "As", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Beban Emisi", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "C O", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Cd", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Cl2", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Co", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "CO (P)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "CO2", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Cr", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Cu", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Debu", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Debu (P)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Effisiensi Pembakaran", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "H2S", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "HC", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "HCl", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "HF", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Hg", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Mn", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "NH3", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "VOC (SC)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "NO", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "NO2", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "NO2-Nox (P)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "NO-NO2", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "NOx", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "NOx-NO2", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "O2", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "O2 (P)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Opasitas", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Partikulat", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Pb", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Sb", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Se", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Sn", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "SO2", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "SO2 (P)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "O2 (ESTB)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Suhu", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Tekanan Udara", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Tl", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Velocity", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Zn", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "CO (Bensin)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiKendaraan::class, "model2" => null],
            ["parameter" => "CO (Gas)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiKendaraan::class, "model2" => null],
            ["parameter" => "CO2 (Bensin)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiKendaraan::class, "model2" => null],
            ["parameter" => "CO-cor (Bensin)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiKendaraan::class, "model2" => null],
            ["parameter" => "HC (Bensin)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiKendaraan::class, "model2" => null],
            ["parameter" => "HC (Gas)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiKendaraan::class, "model2" => null],
            ["parameter" => "O2 (Bensin)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiKendaraan::class, "model2" => null],
            ["parameter" => "Opasitas (Solar)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiKendaraan::class, "model2" => null],
            ["parameter" => "Ergonomi", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganErgonomi::class, "model2" => null],
            ["parameter" => "Get. Badan", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganGetaran::class, "model2" => null],
            ["parameter" => "Get. Bangunan", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganGetaran::class, "model2" => null],
            ["parameter" => "Get. Bangunan (24J)", "requiredCount" => 4, "category" => "4-Udara", "model" => DataLapanganGetaran::class, "model2" => null],
            ["parameter" => "Get. Mesin", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganGetaran::class, "model2" => null],
            ["parameter" => "Get. Tangan Lengan", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganGetaran::class, "model2" => null],
            ["parameter" => "Getaran", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganGetaran::class, "model2" => null],
            ["parameter" => "Getaran (LK) ST", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganGetaranPersonal::class, "model2" => null],
            ["parameter" => "Getaran (LK) TL", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganGetaranPersonal::class, "model2" => null],
            ["parameter" => "K3-KB", "requiredCount" => 1, "category" => "4-Udara", "model" => null, "model2" => null],
            ["parameter" => "K3-KFK", "requiredCount" => 1, "category" => "4-Udara", "model" => null, "model2" => null],
            ["parameter" => "K3-KFPBP", "requiredCount" => 1, "category" => "4-Udara", "model" => null, "model2" => null],
            ["parameter" => "K3-KFS", "requiredCount" => 1, "category" => "4-Udara", "model" => null, "model2" => null],
            ["parameter" => "K3-KRU", "requiredCount" => 1, "category" => "4-Udara", "model" => null, "model2" => null],
            ["parameter" => "K3-KTRTHK", "requiredCount" => 1, "category" => "4-Udara", "model" => null, "model2" => null],
            ["parameter" => "K3-KUV", "requiredCount" => 1, "category" => "4-Udara", "model" => null, "model2" => null],
            ["parameter" => "IKD (CS)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganIklimDingin::class, "model2" => null],
            ["parameter" => "Iklim Kerja Dingin (Cold Stress) - 8 Jam", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganIklimDingin::class, "model2" => null],
            ["parameter" => "ISBB", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganIklimPanas::class, "model2" => null],
            ["parameter" => "ISBB (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganIklimPanas::class, "model2" => null],
            ["parameter" => "E. coli (SWAB)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "S. aureus (SWAB)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Salmonella (SWAB)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Shigella sp. (SWAB)", "requiredCount" => 3, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Iso-Combust", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganIsokinetikHasil::class, "model2" => null],
            ["parameter" => "Iso-Debu", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganIsokinetikHasil::class, "model2" => null],
            ["parameter" => "Iso-DMW", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganIsokinetikHasil::class, "model2" => null],
            ["parameter" => "Isokinetik (All)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganIsokinetikHasil::class, "model2" => null],
            ["parameter" => "Iso-Moisture", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganIsokinetikHasil::class, "model2" => null],
            ["parameter" => "Iso-Percent", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganIsokinetikHasil::class, "model2" => null],
            ["parameter" => "Iso-ResTime", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganIsokinetikHasil::class, "model2" => null],
            ["parameter" => "Iso-Traverse", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganIsokinetikHasil::class, "model2" => null],
            ["parameter" => "Iso-Velo", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganIsokinetikHasil::class, "model2" => null],
            ["parameter" => "Kebisingan", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganKebisingan::class, "model2" => null],
            ["parameter" => "Kebisingan (24 Jam)", "requiredCount" => 7, "category" => "4-Udara", "model" => DataLapanganKebisingan::class, "model2" => null],
            ["parameter" => "Kebisingan (8 Jam)", "requiredCount" => 8, "category" => "4-Udara", "model" => DataLapanganKebisingan::class, "model2" => null],
            ["parameter" => "Kebisingan (P8J)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganKebisinganPersonal::class, "model2" => null],
            ["parameter" => "Aluminium (Al)", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "As", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Asam Asetat", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Asbestos", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Ba", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Carbon Dust", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Cd", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Cl-", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Cl2", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Cl2 (24 Jam)", "requiredCount" => 4, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Cr", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Cu", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Dustfall", "requiredCount" => 2, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Dustfall (S)", "requiredCount" => 2, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Fe", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Fe (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "H2S", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "H2S (24 Jam)", "requiredCount" => 4, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "H2S (3 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "H2S (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "H2SO4", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "HCl", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "HCl (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "HF", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Hg", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Kelembaban", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Laju Ventilasi", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Laju Ventilasi (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Mn", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "NH3", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "NH3 (24 Jam)", "requiredCount" => 4, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "NH3 (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Ni", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "NO2", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "NO2 (24 Jam)", "requiredCount" => 4, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "NO2 (6 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "NO2 (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "NOx", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "O3", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "O3 (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Oil Mist", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Ortho Cresol", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Ox", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Passive NO2", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Passive SO2", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Pb", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Pb (24 Jam)", "requiredCount" => 5, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Pb (6 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Pb (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Pertukaran Udara", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "PM 10 (24 Jam)", "requiredCount" => 5, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "PM 2.5 (24 Jam)", "requiredCount" => 5, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Sb", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Se", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Silica Crystaline 8 Jam", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Sn", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "SO2", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "SO2 (24 Jam)", "requiredCount" => 4, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "SO2 (6 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "SO2 (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Suhu", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "TSP", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "TSP (24 Jam)", "requiredCount" => 5, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "TSP (6 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "TSP (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Zn", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganHidup::class, "model2" => DetailLingkunganKerja::class],
            ["parameter" => "Gelombang Elektro", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganMedanLM::class, "model2" => null],
            ["parameter" => "Medan Listrik", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganMedanLM::class, "model2" => null],
            ["parameter" => "Medan Magnit Statis", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganMedanLM::class, "model2" => null],
            ["parameter" => "Medan Magnet", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganMedanLM::class, "model2" => null],
            ["parameter" => "Power Density", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganMedanLM::class, "model2" => null],
            ["parameter" => "Bacterial Counts", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "E.Coli", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "E.Coli (KB)", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "Fungal Counts", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "Jumlah Bakteri Total", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "T. Bakteri (1 Jam)", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "T. Bakteri (KUDR - 8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "T. Jamur (1 Jam)", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "T. Jamur (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "T. Jamur (KUDR - 8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "T.Bakteri (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "Total Bakteri", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "Total Bakteri (KB)", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "Total Coliform", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "Pencahayaan", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganCahaya::class, "model2" => null],
            ["parameter" => "Psikologi", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganPsikologi::class, "model2" => null],
            ["parameter" => "PM 10", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganKerja::class, "model2" => DataLapanganPartikulatMeter::class],
            ["parameter" => "PM 10 (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganKerja::class, "model2" => DataLapanganPartikulatMeter::class],
            ["parameter" => "PM 2.5", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganKerja::class, "model2" => DataLapanganPartikulatMeter::class],
            ["parameter" => "PM 2.5 (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailLingkunganKerja::class, "model2" => DataLapanganPartikulatMeter::class],
            ["parameter" => "Acetone", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Adverse Odor", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Al. Hidrokarbon", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Al. Hidrokarbon (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Alcohol", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Alkana Gas", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Asetonitril", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Benzene", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Benzene (8 Jam)", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Butanon", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "CH4", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "CH4 (24 Jam)", "requiredCount" => 4, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Cyclohexanone", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "EA", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Eter", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Ethanol", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Etil Benzene", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Fenol", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "HC", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "HC (3 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "HC (6 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "HC (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "HCNM", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => DetailLingkunganHidup::class],
            ["parameter" => "HCNM (3 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => DetailLingkunganHidup::class],
            ["parameter" => "HCNM (6 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => DetailLingkunganHidup::class],
            ["parameter" => "HCNM (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => DetailLingkunganHidup::class],
            ["parameter" => "IPA", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Keton", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Kloroform", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "MEK", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Methacrylates", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Methanol", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Metil Merkaptan", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Metil Merkaptan (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Metil Sulfida", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Metil Sulfida (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "MIBK", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "MK", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Naphthalene", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "N-Hexane (Faktor Kimia)", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "N-Hexane Personil (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Siklohexane - 8 Jam", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Stirena", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Stirena (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Stirone", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Toluene", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Toluene (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Xylene", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Xylene (8 Jam)", "requiredCount" => 3, "category" => "4-Udara", "model" => DetailSenyawaVolatile::class, "model2" => null],
            ["parameter" => "Sinar UV", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSinarUv::class, "model2" => null],
            ["parameter" => "Bacillus C (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "E.Coli (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Enterobacteriaceae (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Kapang Khamir (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Listeria M (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Pseu Aeruginosa (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "S.Aureus (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Salmonella (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Shigella Sp. (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "T.Coli (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Total Kuman (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "TPC (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "Vibrio Ch (Swab Test)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganSwab::class, "model2" => null],
            ["parameter" => "N-Propil Asetat (SC)", "requiredCount" => 1, "category" => "4-Udara", "model" => DataLapanganMedanLM::class, "model2" => null],
            ["parameter" => "Asetaldehid (SC)", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganKerja::class, "model2" => DetailLingkunganHidup::class],
            ["parameter" => "HC (sebagai CH4)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "CH4 (SC)", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
            ["parameter" => "Isopropil Alkohol", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganKerja::class, "model2" => DetailSenyawaVolatile::class],
            ["parameter" => "Metanol", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailLingkunganKerja::class, "model2" => DetailLingkunganHidup::class],
            ["parameter" => "LEGIONELLA", "requiredCount" => 1, "category" => "4-Udara", "model" => DetailMicrobiologi::class, "model2" => null],
            ["parameter" => "VOC Sebagai NMHC", "requiredCount" => 1, "category" => "5-Emisi", "model" => DataLapanganEmisiCerobong::class, "model2" => null],
        ];

        $padatanParam = [
            "Al","Sb","Ag","As","Ba","Fe","B","Cd","Ca","Co","Mn","Na","Ni","Hg","Se","Zn","Tl","Cu","Sn","Pb","Ti","Cr","V","F",
            "NO2","Cr6+","Mo","NO3","CN","Sulfida","Cl-","OG","Chloride",
            "E.Coli (MM)", "Salmonella (MM)", "Shigella Sp. (MM)", "Vibrio Ch (MM)", "S.Aureus"
        ];
        foreach ($padatanParam as $value) {
            $data_parameters[] = [
                "parameter" => $value,
                "requiredCount" => 1,
                "category" => "6-Padatan",
                "model" => null,
                "model2" => null,
            ];
        }

        foreach ($data_parameters as $item) {
            DB::table('required_parameters')->updateOrInsert(
                [
                    'parameter' => $item['parameter'],
                    'category'  => $item['category'],
                ],
                [
                    'required_count' => $item['requiredCount'],
                    'model'          => $item['model'] ?? null,
                    'model2'         => $item['model2'] ?? null,
                    'updated_at'     => Carbon::now(),
                    'created_at'     => Carbon::now(),
                ]
            );
        }

        $this->command->info('RequiredParameter seeder selesai: ' . count($data_parameters) . ' parameter berhasil di-insert.');
    }
}