<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Undangan Career Assessment</title></head>
<body style="margin:0;padding:0;background:#f4f6f9;font-family:Arial,Helvetica,sans-serif;color:#344256;">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f6f9;"><tr><td align="center" style="padding:24px 16px;">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#fff;border:1px solid #dfe5ec;border-radius:6px;overflow:hidden;">
<tr><td style="padding:18px 20px;background:#1f2b3d;color:#fff;"><div style="font-size:15px;font-weight:700;letter-spacing:.1px;">PT INTI SURYA LABORATORIUM</div><div style="margin-top:3px;font-size:11px;color:#b9c7d8;">HRD Division</div></td></tr>
<tr><td style="padding:28px 22px 26px;"><p style="margin:0 0 16px;font-size:13px;line-height:20px;">Yth. Bapak/Ibu <strong>{{ $nama_lengkap }}</strong>,</p><p style="margin:0 0 16px;font-size:13px;line-height:21px;">Terima kasih telah mengirimkan lamaran untuk posisi <strong>{{ $posisi_dilamar }}</strong> di <strong>PT Inti Surya Laboratorium</strong>.</p>@if(!empty($reminder_without_link))<p style="margin:0;font-size:13px;line-height:21px;">Kami mengingatkan bahwa tahap <strong>Career Assessment</strong> Anda belum diselesaikan. Mohon segera menyelesaikan assessment sesuai undangan yang telah kami kirimkan sebelumnya.</p>@else<p style="margin:0 0 16px;font-size:13px;line-height:21px;">Anda dapat melanjutkan ke tahap <strong>Career Assessment</strong> melalui tautan resmi berikut. Link ini berlaku selama 6 x 24 jam sejak undangan assessment dikirim.</p><table role="presentation" cellspacing="0" cellpadding="0" style="margin:20px 0;"><tr><td style="background:#176ee8;border-radius:4px;"><a href="{{ $assessment_url }}" target="_blank" style="display:inline-block;padding:12px 18px;color:#fff;font-size:13px;font-weight:700;text-decoration:none;">Mulai Career Assessment</a></td></tr></table><p style="margin:0 0 6px;font-size:12px;line-height:19px;color:#667588;">Jika tombol tidak dapat dibuka, gunakan tautan berikut:</p><p style="margin:0;font-size:11px;line-height:18px;word-break:break-all;"><a href="{{ $assessment_url }}" target="_blank" style="color:#176ee8;text-decoration:underline;">{{ $assessment_url }}</a></p>@endif</td></tr>
<tr><td style="padding:17px 22px;background:#f8fafc;border-top:1px solid #e2e8ef;"><p style="margin:0 0 4px;font-size:12px;line-height:18px;">Salam,</p><p style="margin:0;font-size:12px;font-weight:700;line-height:18px;">Tim Recruitment HRD<br><span style="font-weight:400;">PT Inti Surya Laboratorium</span></p></td></tr>
</table></td></tr></table>
</body></html>
